### ISSUE TITLE
count check npc not hiding

### ISSUE THREAD

**Issue by pettrs** [YvesW/random-event-hider#6]
![image](https://github.com/YvesW/random-event-hider/assets/75093127/f468f4d5-bcfd-4b1f-9572-02fffee66b34)

the newly added count check npc you get from configuring a Jagex account doesn't hide with the plugin.

**Comment by YvesW** [comment]
I rechecked the code and the MOID; there are no mistakes. Based on the screenshot, it also looks like this is not your own count check (no menu option). I've been playing with others' count check hidden and I've not seen any of them. Based on your previous issues, I think your RL is just broken.
