### ISSUE TITLE
Add Hide Guardian of Armadyl Option

### ISSUE THREAD

**Issue by abanksss** [YvesW/random-event-hider#7]
Can you add an option to hide other players Guardian of Armadyl for the quest while guthix sleeps

**Comment by YvesW** [comment]
Do you happen to have the id(s)? You can use the identificator plugin to get the npc id.

The one chasing me is 13509. I assume this is the only one that's actually a messenger, based on the recent edits on the wiki https://oldschool.runescape.wiki/w/Guardian_of_Armadyl_(Armadyl_communiqu%C3%A9) and the actions on chisel https://chisel.weirdgloop.org/moid/npc_name.html#guardian%20of%20armadyl

**Comment by abanksss** [comment]
![image](https://github.com/user-attachments/assets/a7c00ed0-a9a8-4e9c-9219-e1ef14b2fd8c)
The one following the guy next to me is also 13509.

**Comment by YvesW** [comment]
Added in https://github.com/YvesW/random-event-hider/commit/27743728beb8703da13888c9ccefdfc31ec2472e
Also submitted a PR to the pluginhub. Keep in mind that it needs to be reviewed, so the update might show up between now and 4 weeks. Just wait patiently, and restart your client daily.
